# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alamofire_Param' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'Alamofire', '~> 4.7'

  target 'Alamofire_ParamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Alamofire_ParamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
